# https://prettier.io/docs/options
bracketSameLine: true
printWidth: 120
semi: false

# https://docs.astro.build/en/editor-setup/#prettier
plugins: [prettier-plugin-astro]
overrides:
  - files: "*.astro"
    options:
      parser: astro
