# https://forgejo.org/docs/latest/user/actions/

# https://forgejo.org/docs/latest/user/actions/#secrets
# secrets:
#   SSH_PRIVATE_KEY #?? ssh-keygen -t ed25519 -f ./srv -N '' -C ''

# https://forgejo.org/docs/latest/user/actions/#variables
# vars:
#   DOMAIN
#   SSH_HOST_PORT
#   SSH_HOST_PUBLIC_KEY #?? ssh-keyscan -p <port> <host>

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: docker # https://hub.docker.com/_/node/tags?name=16-bullseye

    steps:
      # https://code.forgejo.org/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y rsync

      # https://docs.astro.build/en/guides/deploy/
      - name: Generate site
        run: |
          npm install
          npm run build

      - name: Import ssh keys
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ vars.SSH_HOST_PUBLIC_KEY }}" > ~/.ssh/authorized_keys

      - name: Copy site to server
        run: |
          rsync \
            --rsh="ssh -p ${{ vars.SSH_HOST_PORT }}" \
            --info=progress2 \
            --verbose \
            --recursive \
            ./dist srv@${{ vars.DOMAIN }}:/srv/sites/${{ vars.DOMAIN }}.new

      - name: Overwrite running site
        run: |
          ssh \
            ssh://srv@${{ vars.DOMAIN }}:${{ vars.SSH_HOST_PORT }} \
            mv /srv/sites/${{ vars.DOMAIN }}.new /srv/sites/${{ vars.DOMAIN }}
