# https://forgejo.org/docs/latest/user/actions/

# https://forgejo.org/docs/latest/user/actions/#secrets
# secrets:
#   SSH_PRIVATE_KEY

# https://forgejo.org/docs/latest/user/actions/#variables
# vars:
#   SSH_PORT
#   DOMAIN

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: docker # https://hub.docker.com/_/node/tags?name=16-bullseye

    steps:
      # https://code.forgejo.org/actions/checkout
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y rsync

      # https://docs.astro.build/en/guides/deploy/
      - name: Generate Astro site
        run: |
          npm install
          npm run build

      - name: Create private key
        run: |
          touch /tmp/ssh.key
          chmod 0600 /tmp/ssh.key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh.key

      - name: Copy site to server
        run: |
          rsync \
            --rsh="ssh -i /tmp/ssh.key" \
            --info=progress2 \
            --verbose \
            --recursive \
            ./dist rsync://srv@${{ vars.DOMAIN }}:${{ vars.SSH_PORT }}/srv/sites/${{ vars.DOMAIN }}.new

      - name: Overwrite running site
        run: |
          ssh \
            -i /tmp/ssh.key \
            ssh://srv@${{ vars.DOMAIN }}:${{ vars.SSH_PORT }} \
            mv /srv/sites/${{ vars.DOMAIN }}.new /srv/sites/${{ vars.DOMAIN }}

      - name: Shred private key
        run: shred /tmp/ssh.key
