# https://forgejo.org/docs/latest/user/actions/

# https://forgejo.org/docs/latest/user/actions/#secrets
# secrets:
#   SSH_PRIVATE_KEY #?? ssh-keygen -t ed25519 -f ./srv -N '' -C ''

# https://forgejo.org/docs/latest/user/actions/#variables
# vars:
#   DOMAIN
#   SSH_HOST
#   SSH_HOST_PORT
#   SSH_HOST_PUBLIC_KEY #?? ssh-keyscan -p <port> <host>

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: docker # https://hub.docker.com/_/node/tags?name=16-bullseye

    steps:
      # https://code.forgejo.org/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y rsync
          npm install

      # https://docs.astro.build/en/guides/deploy/
      - name: Generate site
        run: npm run build

      # https://www.ibm.com/docs/en/zos/3.1.0?topic=daemon-ssh-known-hosts-file-format
      #?? [<host>]:<port> <public key>
      - name: Import ssh keys
        run: |
          mkdir --verbose --parents --mode=0700 ~/.ssh
          cd ~/.ssh
          touch id_ed25519 known_hosts
          chmod --verbose 0600 *
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
          echo "[${{ vars.SSH_HOST }}]:${{ vars.SSH_HOST_PORT }} ${{ vars.SSH_HOST_PUBLIC_KEY }}" > known_hosts
          cd -

      - name: Copy site to server
        run: |
          rsync \
            --verbose \
            --delete \
            --recursive \
            --rsh="ssh -p ${{ vars.SSH_HOST_PORT }}" \
            ./dist/ \
            srv@${{ vars.SSH_HOST }}:/srv/sites/${{ vars.DOMAIN }}.new

      - name: Overwrite running site
        run: |
          ssh ssh://srv@${{ vars.SSH_HOST }}:${{ vars.SSH_HOST_PORT }} '
            rm \
              --verbose \
              --recursive \
              --force \
              /srv/sites/${{ vars.DOMAIN }}

            mv \
              --verbose \
              --no-target-directory \
              /srv/sites/${{ vars.DOMAIN }}.new \
              /srv/sites/${{ vars.DOMAIN }}
          '

      - name: Shred private key
        run: shred --verbose ~/.ssh/id_ed25519
